/**
 * @file Version.h
 * @brief Version information for TCA9548A.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef TCA9548A_VERSION_STRING
#define TCA9548A_VERSION_STRING "1.0.0"
#endif

#ifndef TCA9548A_BUILD_DATE
#define TCA9548A_BUILD_DATE __DATE__
#endif

#ifndef TCA9548A_BUILD_TIME
#define TCA9548A_BUILD_TIME __TIME__
#endif

#ifndef TCA9548A_BUILD_TIMESTAMP
#define TCA9548A_BUILD_TIMESTAMP TCA9548A_BUILD_DATE " " TCA9548A_BUILD_TIME
#endif

#ifndef TCA9548A_GIT_COMMIT
#define TCA9548A_GIT_COMMIT "unknown"
#endif

#ifndef TCA9548A_GIT_STATUS
#define TCA9548A_GIT_STATUS "unknown"
#endif

#ifndef TCA9548A_VERSION_FULL
#define TCA9548A_VERSION_FULL TCA9548A_VERSION_STRING " (" TCA9548A_GIT_COMMIT ", " TCA9548A_BUILD_TIMESTAMP ", " TCA9548A_GIT_STATUS ")"
#endif

namespace TCA9548A {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = TCA9548A_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10000;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10000;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = TCA9548A_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = TCA9548A_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = TCA9548A_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = TCA9548A_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = TCA9548A_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = TCA9548A_VERSION_FULL;

}  // namespace TCA9548A
